import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import { getProviders, getSession, useSession } from "next-auth/react";
import Widgets from '../components/Widgets'
import Feed from '../components/Feed'
import Login from '../components/Login';
import Modal from '../components/Modal';
import { modalState } from '../atoms/modalAtom';
import { useRecoilState } from "recoil";

export default function Home({trendingResults, followResults, providers}) {
  const  {data: session} = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState)

  if(!session) return <Login providers={providers} />

  return (
    <div className="">
      <Head>
          <title>Bird App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/twitter.ico" />
          <meta name="google-site-verification" content="bmzE7mLj3GzNVnVaF7m7G17dHy39AW9qJzW8KqDf9oU" />
      </Head>

      <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
          <Sidebar />
          <Feed />
          <Widgets 
            trendingResults={trendingResults} 
            followResults={followResults}
          />
          {isOpen && <Modal />}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const trendingResults = await fetch("https://www.jsonkeeper.com/b/NKEV").then(
    (res) => res.json()
  );
  const followResults = await fetch("https://www.jsonkeeper.com/b/WWMJ").then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(context);

  // here you must return the session
  return {
    props: {
      trendingResults: trendingResults,
      followResults: followResults,
      providers,
      session,
    },
  };
}
