import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
// import Widgets from '../components/Widgets'
import Feed from '../components/Feed'

const followComponent = [
  {
    userImg: "https://rb.gy/urakiy",
    username: "SpaceX",
    tag: "@SpaceX",
  },
  {
    userImg: "https://rb.gy/aluxgh",
    username: "Elon Musk",
    tag: "@elonmusk",
  },
  {
    userImg: "https://rb.gy/zyvazm",
    username: "Tesla",
    tag: "@Tesla",
  },
];

const trendingComponent = [
  {
    heading: "T20 World Cup 2021 · LIVE",
    description:
      "NZvAUS: New Zealand and Australia clash in the T20 World Cup final",
    img: "https://rb.gy/d9yjtu",
    tags: ["#T20WorldCupFinal, ", "Kane Williamson"],
  },
  {
    heading: "Trending in United Arab Emirates",
    description: "#earthquake",
    img: "https://rb.gy/jvuy4v",
    tags: ["#DubaiAirshow, ", "#gessdubai"],
  },
  {
    heading: "Trending in Digital Creators",
    description: "tubbo and quackity",
    img: "",
    tags: ["QUACKITY AND TUBBO,"],
  },
];

export default function Home() {
    return (
        <div className="">
            <Head>
                <title>Twitter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-black min-h-screen flex max-w-[1500px] mx-auto">
                <Sidebar />
                <Feed />
                {/* <Widgets /> */}
                {/* <Widgets
                trendingComponent={trendingComponent}
                followComponent={followComponent}
                /> */}
            </main>
        </div>
    )
}

export async function getServerSideProps() {

}
